# Source: https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
cache:
  apt: false
  packages: false
  timeout: 3000
apt_packages:
  - openjdk-7-jre
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
  - sudo R CMD javareconf
r:
  - release
  - devel
bioc_required: true
use_bioc: true