# Source: https://docs.travis-ci.com/user/languages/r
language: r
addons:
  apt:
    packages:
      - r-cran-rjava
before_install:
  - R CMD javareconf -e
cache:
  apt: true
  packages: true
  timeout: 3000
r:
  - release
  - devel
bioc_required: true
use_bioc: true