# Source: https://docs.travis-ci.com/user/languages/r
language: r
cache:
  apt: true
  packages: true
  timeout: 3000
r:
  - release
  - devel
before_install:
  - export LD_LIBRARY_PATH=java-8-openjdk-amd64/jre/lib/amd64/server:$LD_LIBRARY_PATH
bioc_required: true
use_bioc: true