# Source: https://docs.travis-ci.com/user/languages/r
language: r
cache:
  apt: true
  packages: true
  timeout: 3000
r:
  - release
  - devel
install:
  - sudo R CMD javareconf
bioc_required: true
use_bioc: true